name: simple-python-script
desc: Program description
cmd: |
  pip install ultralytics --no-deps
  python3 src/evaluate.py
inputs:
  - src/
outputs:
  - runs/
env:
  docker: system-python-3-10
cloud-instance-type: gt4.1 # T4, поменять на c1.4 если не тренируете модель
s3-mounts:
  - bt15mrdpleurdj659o9m  # например: abcdef1234567890
flags:
  - attach-project-disk 